name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2024-04-20
          override: true
          components: rust-src, rustfmt, clippy
      - name: Install WebAssembly target
        run: rustup target add wasm32-unknown-unknown
      - name: Install MUSL target
        run: rustup target add x86_64-unknown-linux-musl
      - name: Build Client
        working-directory: ./client
        run: cargo build --target wasm32-unknown-unknown --locked
      - name: Build Server
        working-directory: ./server
        run: cargo build --target x86_64-unknown-linux-musl --locked
      - name: Build Sprite Sheet Util
        working-directory: ./sprite_sheet_util
        run: cargo build --locked
